# Generated by Django 4.2.3 on 2023-07-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='lastname',
        ),
        migrations.AddField(
            model_name='medication',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='medication_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='pap_application_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='pap_eligibility_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='pap_info_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
