# Generated by Django 4.2.3 on 2023-07-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_remove_medication_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='manufacturer_name',
            new_name='pap_name',
        ),
    ]
